version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app/public:/var/www/html
      - ./nginx/default.conf:/etc/nginx/default.conf
    depends_on:
      - php

  php:
    build: .
    volumes:
      - ./app/public:/var/www/html
    expose:
      - "9000"

  db:
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: qaNCElSKpuGcyzbzTFHMEYLkZnQzWQUe
      MYSQL_DATABASE: railway
      MYSQL_USER: root
      MYSQL_PASSWORD: qaNCElSKpuGcyzbzTFHMEYLkZnQzWQUe
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
